"""Zones API module for hass-mcp.

This module provides functions for interacting with Home Assistant zones.
Zones are geographic areas defined by GPS coordinates for location-based automations.
"""

import logging
from typing import Any

from app.api.base import BaseAPI
from app.core.cache.decorator import cached, invalidate_cache
from app.core.cache.ttl import TTL_VERY_LONG
from app.core.decorators import handle_api_errors

logger = logging.getLogger(__name__)


class ZonesAPI(BaseAPI):
    """API client for Home Assistant zone operations."""

    pass


_zones_api = ZonesAPI()


@handle_api_errors
@cached(ttl=TTL_VERY_LONG, key_prefix="zones")
async def list_zones() -> list[dict[str, Any]]:
    """
    Get list of all zones (GPS coordinates).

    Returns:
        List of zone dictionaries containing:
        - id: Unique identifier for the zone
        - name: Display name of the zone
        - latitude: Latitude coordinate (-90 to 90)
        - longitude: Longitude coordinate (-180 to 180)
        - radius: Zone radius in meters
        - icon: Zone icon (if available)
        - passive: Whether the zone is passive

    Example response:
        [
            {
                "id": "home",
                "name": "Home",
                "latitude": 37.7749,
                "longitude": -122.4194,
                "radius": 100,
                "icon": "mdi:home",
                "passive": false
            }
        ]

    Note:
        Zones are geographic areas defined by GPS coordinates.
        Used for location-based automations and device tracking.

    Best Practices:
        - Use this to discover available zones
        - Check zone coordinates and radius for location-based automations
        - Use zones for location-based device tracking and automations
    """
    return await _zones_api.get("/api/config/zone_registry")


@handle_api_errors
@invalidate_cache(pattern="zones:*")
async def create_zone(
    name: str,
    latitude: float,
    longitude: float,
    radius: float,
    icon: str | None = None,
    passive: bool = False,
) -> dict[str, Any]:
    """
    Create a new zone.

    Args:
        name: Display name for the zone (required)
        latitude: Latitude coordinate (-90 to 90) (required)
        longitude: Longitude coordinate (-180 to 180) (required)
        radius: Zone radius in meters (required, must be positive)
        icon: Optional zone icon (e.g., 'mdi:home')
        passive: Whether the zone is passive (default: False)

    Returns:
        Created zone dictionary with zone_id and configuration

    Examples:
        # Create a home zone
        zone = await create_zone("Home", 37.7749, -122.4194, 100, "mdi:home")

        # Create a work zone
        zone = await create_zone("Work", 37.7849, -122.4094, 200)

        # Create a passive zone
        zone = await create_zone("School", 37.7949, -122.3994, 150, passive=True)

    Note:
        Zone IDs are automatically generated by Home Assistant.
        GPS coordinates are validated to be within valid ranges.
        Radius must be positive.

    Error Handling:
        - Validates latitude is between -90 and 90
        - Validates longitude is between -180 and 180
        - Validates radius is positive
        - Handles duplicate zone names

    Best Practices:
        - Use descriptive names for zones
        - Set appropriate radius based on location size
        - Use icons for visual identification in dashboards
        - Set passive=True for zones that should not trigger automations
    """
    # Validate GPS coordinates
    if not -90 <= latitude <= 90:
        return {"error": f"Latitude must be between -90 and 90, got: {latitude}"}

    if not -180 <= longitude <= 180:
        return {"error": f"Longitude must be between -180 and 180, got: {longitude}"}

    if radius <= 0:
        return {"error": f"Radius must be positive, got: {radius}"}

    payload: dict[str, Any] = {
        "name": name,
        "latitude": latitude,
        "longitude": longitude,
        "radius": radius,
        "passive": passive,
    }

    if icon:
        payload["icon"] = icon

    return await _zones_api.post("/api/config/zone_registry", data=payload)


@handle_api_errors
@invalidate_cache(pattern="zones:*")
async def update_zone(
    zone_id: str,
    name: str | None = None,
    latitude: float | None = None,
    longitude: float | None = None,
    radius: float | None = None,
    icon: str | None = None,
) -> dict[str, Any]:
    """
    Update an existing zone.

    Args:
        zone_id: The zone ID to update
        name: Optional new name for the zone
        latitude: Optional new latitude coordinate (-90 to 90)
        longitude: Optional new longitude coordinate (-180 to 180)
        radius: Optional new radius in meters (must be positive)
        icon: Optional new icon

    Returns:
        Updated zone dictionary

    Examples:
        # Update zone name
        zone = await update_zone("home", name="My Home")

        # Update zone location
        zone = await update_zone("work", latitude=37.7849, longitude=-122.4094)

        # Update zone radius
        zone = await update_zone("home", radius=150)

        # Update multiple fields
        zone = await update_zone("work", name="Office", radius=200, icon="mdi:office")

    Note:
        Only provided fields will be updated. Fields not provided remain unchanged.
        GPS coordinates and radius are validated if provided.

    Error Handling:
        - Validates latitude is between -90 and 90 (if provided)
        - Validates longitude is between -180 and 180 (if provided)
        - Validates radius is positive (if provided)
        - Returns error if no fields provided

    Best Practices:
        - Get zone first with list_zones to verify zone_id
        - Update one field at a time or all together
        - Verify GPS coordinates are correct before updating
    """
    # Validate GPS coordinates if provided
    if latitude is not None and not -90 <= latitude <= 90:
        return {"error": f"Latitude must be between -90 and 90, got: {latitude}"}

    if longitude is not None and not -180 <= longitude <= 180:
        return {"error": f"Longitude must be between -180 and 180, got: {longitude}"}

    if radius is not None and radius <= 0:
        return {"error": f"Radius must be positive, got: {radius}"}

    payload: dict[str, Any] = {}
    if name is not None:
        payload["name"] = name
    if latitude is not None:
        payload["latitude"] = latitude
    if longitude is not None:
        payload["longitude"] = longitude
    if radius is not None:
        payload["radius"] = radius
    if icon is not None:
        payload["icon"] = icon

    if not payload:
        return {
            "error": "At least one field (name, latitude, longitude, radius, icon) must be provided"
        }

    return await _zones_api.post(f"/api/config/zone_registry/{zone_id}", data=payload)


@handle_api_errors
@invalidate_cache(pattern="zones:*")
async def delete_zone(zone_id: str) -> dict[str, Any]:
    """
    Delete a zone.

    Args:
        zone_id: The zone ID to delete

    Returns:
        Response from the delete operation with status and zone_id

    Examples:
        zone_id="work" - delete zone with ID work

    Note:
        ⚠️ This permanently deletes the zone. There is no undo.
        System zones (like 'home') may not be deletable.
        Make sure no automations or device tracking depend on this zone.

    Best Practices:
        - Check for dependencies before deleting
        - Verify zone_id is correct before deletion
        - Consider updating zone instead of deleting if possible
        - List zones first to ensure correct zone_id
    """
    await _zones_api.delete(f"/api/config/zone_registry/{zone_id}")
    return {"status": "deleted", "zone_id": zone_id}
