"""Area MCP tools for hass-mcp.

This module provides MCP tools for interacting with Home Assistant areas.
These tools are thin wrappers around the areas API layer.
"""

import logging
from typing import Any

from app.api.areas import (
    create_area,
    delete_area,
    get_area_entities,
    get_area_summary,
    get_areas,
    update_area,
)

logger = logging.getLogger(__name__)


async def list_areas_tool() -> list[dict[str, Any]]:
    """
    Get a list of all areas in Home Assistant.

    Returns:
        List of area dictionaries containing:
        - area_id: Unique identifier for the area
        - name: Display name of the area
        - aliases: List of aliases for the area
        - picture: Path to area picture (if available)

    Examples:
        Returns all areas with their configuration

    Best Practices:
        - Use this to discover available areas before operations
        - Check area names and aliases to find specific areas
    """
    logger.info("Getting list of areas")
    return await get_areas()


async def get_area_entities_tool(area_id: str) -> list[dict[str, Any]]:
    """
    Get all entities belonging to a specific area.

    Args:
        area_id: The area ID to get entities for

    Returns:
        List of entities in the specified area

    Examples:
        area_id="living_room" - get all entities in the living room area

    Note:
        Entities are filtered by their area_id attribute.
        Returns empty list if area has no entities or area doesn't exist.

    Best Practices:
        - Use this to see what entities are in an area before deleting it
        - Use to organize entities by location
    """
    logger.info(f"Getting entities for area: {area_id}")
    return await get_area_entities(area_id)


async def create_area_tool(
    name: str,
    aliases: list[str] | None = None,
    picture: str | None = None,
) -> dict[str, Any]:
    """
    Create a new area.

    Args:
        name: Display name for the area (required)
        aliases: Optional list of aliases for the area
        picture: Optional path to area picture

    Returns:
        Created area dictionary with area_id and configuration

    Examples:
        name="Living Room" - create area with just name
        name="Living Room", aliases=["lounge", "salon"] - create area with aliases

    Note:
        Area IDs are automatically generated by Home Assistant.
        Duplicate names are allowed but may cause confusion.

    Best Practices:
        - Use descriptive names for areas
        - Add aliases for common alternative names
        - Use pictures to visually identify areas in dashboards
    """
    logger.info(f"Creating area: {name}")
    return await create_area(name, aliases, picture)


async def update_area_tool(
    area_id: str,
    name: str | None = None,
    aliases: list[str] | None = None,
    picture: str | None = None,
) -> dict[str, Any]:
    """
    Update an existing area.

    Args:
        area_id: The area ID to update
        name: Optional new name for the area
        aliases: Optional new list of aliases (replaces existing)
        picture: Optional new picture path

    Returns:
        Updated area dictionary

    Examples:
        area_id="living_room", name="Family Room" - update area name
        area_id="living_room", aliases=["lounge", "salon"] - update aliases

    Note:
        Only provided fields will be updated. Fields not provided remain unchanged.
        If aliases is provided, it replaces all existing aliases.

    Best Practices:
        - Get area first with list_areas to verify area_id
        - Update one field at a time or all together
        - Remember that aliases replace existing ones
    """
    logger.info(f"Updating area: {area_id}")
    return await update_area(area_id, name, aliases, picture)


async def delete_area_tool(area_id: str) -> dict[str, Any]:
    """
    Delete an area.

    Args:
        area_id: The area ID to delete

    Returns:
        Response from the delete operation

    Examples:
        area_id="living_room" - delete area with ID living_room

    Note:
        ⚠️ This permanently deletes the area. There is no undo.
        Entities associated with this area will have their area_id removed.
        Make sure to check for entities before deleting, or use get_area_entities first.

    Best Practices:
        - Check for entities with get_area_entities before deleting
        - Verify area_id is correct before deletion
        - Consider updating entities to a new area instead of deleting
    """
    logger.info(f"Deleting area: {area_id}")
    return await delete_area(area_id)


async def get_area_summary_tool() -> dict[str, Any]:
    """
    Get summary of all areas with device/entity distribution.

    Returns:
        Dictionary containing:
        - total_areas: Total number of areas
        - areas: Dictionary mapping area_id to area summary with:
            - name: Area name
            - entity_count: Number of entities in the area
            - domain_counts: Dictionary of domain counts (e.g., {"light": 3, "switch": 2})

    Examples:
        Returns summary of all areas with entity distribution

    Best Practices:
        - Use this to understand entity distribution across areas
        - Identify areas with no entities
        - Analyze domain distribution by area
    """
    logger.info("Getting area summary")
    return await get_area_summary()
