"""Zones MCP tools for hass-mcp.

This module provides MCP tools for interacting with Home Assistant zones.
These tools are thin wrappers around the zones API layer.
"""

import logging
from typing import Any

from app.api.zones import create_zone, delete_zone, list_zones, update_zone

logger = logging.getLogger(__name__)


async def list_zones_tool() -> list[dict[str, Any]]:
    """
    Get a list of all zones (GPS coordinates) in Home Assistant.

    Returns:
        List of zone dictionaries containing:
        - id: Unique identifier for the zone
        - name: Display name of the zone
        - latitude: Latitude coordinate (-90 to 90)
        - longitude: Longitude coordinate (-180 to 180)
        - radius: Zone radius in meters
        - icon: Zone icon (if available)
        - passive: Whether the zone is passive

    Examples:
        Returns all zones with their GPS coordinates and configuration

    Note:
        Zones are geographic areas defined by GPS coordinates.
        Used for location-based automations and device tracking.

    Best Practices:
        - Use this to discover available zones before operations
        - Check zone coordinates and radius for location-based automations
        - Use zones for location-based device tracking and automations
    """
    logger.info("Getting list of zones")
    return await list_zones()


async def create_zone_tool(
    name: str,
    latitude: float,
    longitude: float,
    radius: float,
    icon: str | None = None,
    passive: bool = False,
) -> dict[str, Any]:
    """
    Create a new zone.

    Args:
        name: Display name for the zone (required)
        latitude: Latitude coordinate (-90 to 90) (required)
        longitude: Longitude coordinate (-180 to 180) (required)
        radius: Zone radius in meters (required, must be positive)
        icon: Optional zone icon (e.g., 'mdi:home')
        passive: Whether the zone is passive (default: False)

    Returns:
        Created zone dictionary with zone_id and configuration

    Examples:
        name="Home", latitude=37.7749, longitude=-122.4194, radius=100, icon="mdi:home"
        name="Work", latitude=37.7849, longitude=-122.4094, radius=200
        name="School", latitude=37.7949, longitude=-122.3994, radius=150, passive=True

    Note:
        Zone IDs are automatically generated by Home Assistant.
        GPS coordinates are validated to be within valid ranges.
        Radius must be positive.

    Best Practices:
        - Use descriptive names for zones
        - Set appropriate radius based on location size
        - Use icons for visual identification in dashboards
        - Set passive=True for zones that should not trigger automations
    """
    logger.info(f"Creating zone: {name} at ({latitude}, {longitude}) with radius {radius}")
    return await create_zone(name, latitude, longitude, radius, icon, passive)


async def update_zone_tool(
    zone_id: str,
    name: str | None = None,
    latitude: float | None = None,
    longitude: float | None = None,
    radius: float | None = None,
    icon: str | None = None,
) -> dict[str, Any]:
    """
    Update an existing zone.

    Args:
        zone_id: The zone ID to update
        name: Optional new name for the zone
        latitude: Optional new latitude coordinate (-90 to 90)
        longitude: Optional new longitude coordinate (-180 to 180)
        radius: Optional new radius in meters (must be positive)
        icon: Optional new icon

    Returns:
        Updated zone dictionary

    Examples:
        zone_id="home", name="My Home" - update zone name
        zone_id="work", latitude=37.7849, longitude=-122.4094 - update zone location
        zone_id="home", radius=150 - update zone radius
        zone_id="work", name="Office", radius=200, icon="mdi:office" - update multiple fields

    Note:
        Only provided fields will be updated. Fields not provided remain unchanged.
        GPS coordinates and radius are validated if provided.

    Best Practices:
        - Get zone first with list_zones to verify zone_id
        - Update one field at a time or all together
        - Verify GPS coordinates are correct before updating
    """
    logger.info(f"Updating zone: {zone_id}")
    return await update_zone(zone_id, name, latitude, longitude, radius, icon)


async def delete_zone_tool(zone_id: str) -> dict[str, Any]:
    """
    Delete a zone.

    Args:
        zone_id: The zone ID to delete

    Returns:
        Response from the delete operation

    Examples:
        zone_id="work" - delete zone with ID work

    Note:
        ⚠️ This permanently deletes the zone. There is no undo.
        System zones (like 'home') may not be deletable.
        Make sure no automations or device tracking depend on this zone.

    Best Practices:
        - Check for dependencies before deleting
        - Verify zone_id is correct before deletion
        - Consider updating zone instead of deleting if possible
        - List zones first to ensure correct zone_id
    """
    logger.info(f"Deleting zone: {zone_id}")
    return await delete_zone(zone_id)
